---
title: "Reading Delimited Data"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

Task - 2

Part A- Glass Data

1. 
```{r}
library(tidyverse)

# Read the Glass dataset directly from URL
glass <- read_csv(
  "https://www4.stat.ncsu.edu/~online/datasets/glass.data",
  col_names = c("Id","RI","Na","Mg","Al","Si","K","Ca","Ba","Fe","Type_of_glass")
)

# Print tibble
glass
```

2. 
```{r}
glass <- glass %>%
  mutate(Type_of_glass = case_when(
    Type_of_glass == 1 ~ "building_windows_float_processed",
    Type_of_glass == 2 ~ "building_windows_non_float_processed",
    Type_of_glass == 3 ~ "vehicle_windows_float_processed",
    Type_of_glass == 4 ~ "vehicle_windows_non_float_processed",
    Type_of_glass == 5 ~ "containers",
    Type_of_glass == 6 ~ "tableware",
    Type_of_glass == 7 ~ "headlamps"
  ))

glass
```
3. 
```{r}
glass_filtered <- glass %>%
  filter(Fe < 0.2 & Type_of_glass %in% c("tableware", "headlamps"))

glass_filtered

```

---
title: "Yeast Data"
format: html
---

Part B : Yeast Data

1. 
```{r}

yeast <- read_table(
  "https://www4.stat.ncsu.edu/~online/datasets/yeast.data",
  col_names = c("seq_name","mcg","gvh","alm","mit","erl","pox","vac","nuc","class")
)

yeast
```

2. 
```{r}
yeast <- yeast %>% select(-seq_name, -nuc)

yeast
```
3. 
```{r}
yeast_summary <- yeast %>%
  group_by(class) %>%
  summarise(across(
    c(mcg, gvh, alm, mit, erl, pox, vac),
    list(mean = mean, median = median)
  ))

yeast_summary
```
